<meta name="google-site-verification" content="uRPBDhWDlYYizQtyBR4XTRwkmiwRNNNqkeVACBfVf0Y" />


title: Youshua Kesting
author: Youshua Kesting

show_excerpts: false
theme: jekyll-theme-primer

github:
  is_project_page: false
